spring.application.name=api-gateway
server.port=8089

# =========================================================
# MS CITAS
# =========================================================
spring.cloud.gateway.routes[0].id=ms-citas
spring.cloud.gateway.routes[0].uri=http://3.88.9.17:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/citas/**

# =========================================================
# MS PACIENTES
# =========================================================
spring.cloud.gateway.routes[1].id=ms-pacientes
spring.cloud.gateway.routes[1].uri=http://54.237.95.110:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/pacientes/**

# =========================================================
# MS MEDICOS
# =========================================================
spring.cloud.gateway.routes[2].id=ms-medicos
spring.cloud.gateway.routes[2].uri=http://52.7.39.56:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/medicos/**

# =========================================================
# MS SALAS
# =========================================================
spring.cloud.gateway.routes[3].id=ms-salas
spring.cloud.gateway.routes[3].uri=http://44.203.229.1:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/salas/**

# =========================================================
# MS HISTORIAL
# =========================================================
spring.cloud.gateway.routes[4].id=ms-historial
spring.cloud.gateway.routes[4].uri=http://44.200.40.70:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/historial/**

# =========================================================
# MS NOTIFICACIONES
# =========================================================
spring.cloud.gateway.routes[5].id=ms-notificaciones
spring.cloud.gateway.routes[5].uri=http://32.192.180.163:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/notificaciones/**

# =========================================================
# LOGGING
# =========================================================
logging.level.org.springframework.cloud.gateway=DEBUG

# =========================================================
# CORS
# =========================================================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=false